trigger:
- master

pool:
  name: 'agentpool'

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'ado-to-aks'
    azureResourceGroup: 'testing'
    kubernetesCluster: 'restrictedAKS'
    command: 'apply'
    arguments: '-f deploy.yaml'